---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mytetris-deploy
spec:
  replicas: 4
  selector:
    matchLabels:
      app: mytetris-prod
  template:
    metadata:
      labels:
        app: mytetris-prod
    spec:
      containers:
        - name: cont1
          image: sandeepkr98/mytetris:v1
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "200m"
